title: Neverwhere
email: 
description: >- 

include:
  - _pages

baseurl: ''
url: ""

paginate: 4
paginate_path: "/blog/:num/"

github_username:  d-krylov

avatar: /assets/images/avatar.jpg
page404: /assets/images/404.jpg

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll_include_plugin
