baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Neverwhere'

[params]
avatar = "/images/avatar.jpg"
math = true

[markup]
  [markup.highlight]
    style = "friendly"
    lineNos = true
    lineNumbersInTable = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]


[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"