\NeedsTeXFormat{LaTeX2e} 
\ProvidesClass{cv_template}[cv_template class]

\LoadClass[oneside]{article}

\RequirePackage{geometry}
\RequirePackage{paracol}
\RequirePackage{anyfontsize}
\RequirePackage{xcolor}
\RequirePackage{blindtext}
\RequirePackage{setspace}
\RequirePackage{enumitem}
\RequirePackage{lipsum}
\RequirePackage{scrextend}
\RequirePackage{fontawesome5}
\RequirePackage[hidelinks, colorlinks=true, urlcolor=blue!70]{hyperref}

\geometry{
  a4paper,
  left=1cm,
  right=1cm,
  top=1cm,
  bottom=1cm
}